### PR TITLE
Notifications via Web Push API

### PR DESCRIPTION
**Pull request by mariushegele**
Deployment:

1. `make vapid_app_key`
2. copy the app key into `frontend/www/main.js` -> `applicationServerKey`
3. `make backend`
4. `make frontend`
5.  open `localhost:4000` in browser
6. trigger a notification via `notification_handler.push(notification)`

see `controller/notfication_handler` main for an example

### CODE REVIEW

**Comment by Ovakefali13** [comment]
Why did you fix the singleton file again?

**Comment by mariushegele** [comment]
> Why did you fix the singleton file again?

I merged in your fix and applied to my new sources.

**Comment by Ovakefali13** [comment]
I see

**Comment by mariushegele** [comment]
A use case could import the `notification_handler` and post a message or notification via `post`

**Pull request merged**
