### PR TITLE
Setup Jest for Frontend testing

### PR DESCRIPTION
**Pull request by fionnfuchs**
# Get Started 
Define frontend javascript unit test suites like this: <name>.test.js in any subdirectory of frontend. Tests support jquery. In the test suite file define unit tests like this: 
```
test('Jest works', () => {
  expect(1).toBe(1);
});
```
To access functions from your javascript file import it with require("./<pathtofile>") at the top of the test suite. It is then executed in the beginning and all its functions are available in the test suite. 
 
## Running Tests 
Run `make` to (by default) execute all python and jest tests. The makefile has been naively modified to do so. Run `npm run test` in the frontend directory to execute just the frontend js tests.

### CODE REVIEW

**Comment by fionnfuchs** [comment]
Test fails because Travis does not have the jest package which is needed for testing specified in package.json.

**Comment by fionnfuchs** [comment]
A little hotfix ;) @mariushegele Do you have an idea how to do this elegantly?

**Comment by mariushegele** [comment]
Why isn't Travis running?

**Comment by fionnfuchs** [comment]
You broke it I guess...

**Comment by mariushegele** [comment]
They are received, but not run. Same happening on other PR's. 
https://travis-ci.com/github/Ovakefali13/buerro/pull_requests

**Comment by mariushegele** [comment]
Finally. That was a hassle.

**Pull request merged**
